CREATE TABLE CLIENTE (
	CD_CLIENTE NUMERIC(4),
	NM_CLIENTE VARCHAR(50) NOT NULL,
	DS_ENDERECO VARCHAR(70) NOT NULL,
	CD_MUNICIPIO NUMERIC(5),
	SG_ESTADO CHAR(2),
	NR_CEP VARCHAR(8),
	NR_DDD NUMERIC(3),
	NR_FONE NUMERIC(7),
	IE_SEXO CHAR(1),
	CONSTRAINT CLIENTE_PK PRIMARY KEY (CD_CLIENTE),
	CONSTRAINT CLIENTE_SG_ESTADO_FK FOREIGN KEY (SG_ESTADO) REFERENCES ESTADO (SG_ESTADO),
	CONSTRAINT CLIENTE_IE_SEXO_CK CHECK (IE_SEXO IN ('F', 'M'))
);

--Drop TABLE cliente

CREATE TABLE HISTORICO (
	CD_CLIENTE NUMERIC(4),
	DT_COMPRA DATE,
	VL_COMPRA NUMERIC(12, 2),
	CONSTRAINT HISTORICO_PK PRIMARY KEY (CD_CLIENTE, DT_COMPRA)
);

CREATE TABLE ESTADO (
	SG_ESTADO CHAR(2),
	NM_ESTADO VARCHAR(35),
	CONSTRAINT ESTADO_SG_ESTADO_PK PRIMARY KEY (SG_ESTADO),
	CONSTRAINT ESTADO_NM_ESTADO_UN UNIQUE (NM_ESTADO)
);